# Generated by Django 2.2 on 2022-04-15 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sched_maint_app', '0002_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='status',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
    ]
